[package]
name = "desuilabs"
version = "0.0.0"
published-at = "0x1abc7dd23ca95e3780c84825e57ba06a06816d74860d01dbedef6411c2fbb57d"

[dependencies.Launchpad]
git = "https://github.com/Origin-Byte/nft-protocol.git"
subdir = "contracts/launchpad"
rev = "testnet"

[dependencies.NftProtocol]
git = "https://github.com/Origin-Byte/nft-protocol.git"
subdir = "contracts/nft_protocol"
rev = "testnet"

[dependencies.LiquidityLayerV1]
git = "https://github.com/Origin-Byte/nft-protocol.git"
subdir = "contracts/liquidity_layer_v1"
rev = "testnet"

[addresses]
desuilabs = "0x1abc7dd23ca95e3780c84825e57ba06a06816d74860d01dbedef6411c2fbb57d"
